package cn.edu.hzvtc.entity;

import javax.validation.constraints.Email;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_employee.emp_id
     *
     * @mbg.generated Tue Jun 08 12:53:44 CST 2021
     */
    private Integer empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_employee.emp_name
     *
     * @mbg.generated Tue Jun 08 12:53:44 CST 2021
     */
    @Pattern(regexp = "([\\u4e00-\\u9fa5_a-zA-Z]{2,15})",message = "用户名必须由2~5位的中或英文字母组成!!")
    private String empName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_employee.emp_email
     *
     * @mbg.generated Tue Jun 08 12:53:44 CST 2021
     */

    @Pattern(regexp = "(^[a-zA-Z0-9_-]+@[a-zA-Z0-9_-]+(\\.[a-zA-Z0-9_-]+)+$)",message = "Email格式不正确!")
    private String empEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_employee.emp_gender
     *
     * @mbg.generated Tue Jun 08 12:53:44 CST 2021
     */
    @NotNull(message = "请选择性别！")
    private Boolean empGender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_employee.d_id
     *
     * @mbg.generated Tue Jun 08 12:53:44 CST 2021
     */
    @NotNull(message = "请选择部门!")
    private Integer dId;

    /*关联对象*/

    private Department department;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employee.emp_id
     *
     * @return the value of tbl_employee.emp_id
     *
     * @mbg.generated Tue Jun 08 12:53:44 CST 2021
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employee.emp_id
     *
     * @param empId the value for tbl_employee.emp_id
     *
     * @mbg.generated Tue Jun 08 12:53:44 CST 2021
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employee.emp_name
     *
     * @return the value of tbl_employee.emp_name
     *
     * @mbg.generated Tue Jun 08 12:53:44 CST 2021
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employee.emp_name
     *
     * @param empName the value for tbl_employee.emp_name
     *
     * @mbg.generated Tue Jun 08 12:53:44 CST 2021
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employee.emp_email
     *
     * @return the value of tbl_employee.emp_email
     *
     * @mbg.generated Tue Jun 08 12:53:44 CST 2021
     */
    public String getEmpEmail() {
        return empEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employee.emp_email
     *
     * @param empEmail the value for tbl_employee.emp_email
     *
     * @mbg.generated Tue Jun 08 12:53:44 CST 2021
     */
    public void setEmpEmail(String empEmail) {
        this.empEmail = empEmail == null ? null : empEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employee.emp_gender
     *
     * @return the value of tbl_employee.emp_gender
     *
     * @mbg.generated Tue Jun 08 12:53:44 CST 2021
     */
    public Boolean getEmpGender() {
        return empGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employee.emp_gender
     *
     * @param empGender the value for tbl_employee.emp_gender
     *
     * @mbg.generated Tue Jun 08 12:53:44 CST 2021
     */
    public void setEmpGender(Boolean empGender) {
        this.empGender = empGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employee.d_id
     *
     * @return the value of tbl_employee.d_id
     *
     * @mbg.generated Tue Jun 08 12:53:44 CST 2021
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employee.d_id
     *
     * @param dId the value for tbl_employee.d_id
     *
     * @mbg.generated Tue Jun 08 12:53:44 CST 2021
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }

    public Department getDepartment() {
        return department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    public Employee(Integer empId, String empName, String empEmail, Boolean empGender, Integer dId) {
        this.empId = empId;
        this.empName = empName;
        this.empEmail = empEmail;
        this.empGender = empGender;
        this.dId = dId;
    }

    public Employee() {
    }

    @Override
    public String toString() {
        return "Employee{" +
                "empId=" + empId +
                ", empName='" + empName + '\'' +
                ", empEmail='" + empEmail + '\'' +
                ", empGender=" + empGender +
                ", dId=" + dId +
                ", department=" + department +
                '}';
    }
}